---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалить товар из корзины
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - На странице товара и в каталоге нужно выводить название, рейтинг, цена со скидкой и без нее.
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь мобильную версию
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
  - Магазин будет SPA-приложение, которое не перезагружает страницу.
  - Корзина будет хранится в сессии браузера.
implicit:
  - Сайт должен быть адаптирован под все виды устройств 
  - Пользователь должен оставить,какие то личные данные о себе для связи ( email или номе телефона )
  - Нужна форма для заполнения личных даных 
  - У товара должна быть цена 
  - Должна быть возможность удалять товары из корзины
  - Должна быть кнопка заказать товар
